site_name: ACL Ethics
nav:
  - Home: index.md
  - Roles:
        - Roles: roles/index.md
        - roles/authors.md
        - Instructors: roles/instructors.md
        - roles/organizers.md
        - roles/researchers.md
        - Reviewers: roles/reviewers.md
  - Tutorials:
        - tutorials/index.md
        - "Past tutorials":
          - tutorials/EACL_2023.md  
        - "Upcoming tutorials":
          - tutorials/ACL_2025.md
  - Resources:
        - resources/index.md
        - "Reading List":
          - "The Whole List": resources/ethics-reading-list/index.md
          - "topic-biases": resources/ethics-reading-list/t-biases.md
          - "topic-crowdsourcing-issues": resources/ethics-reading-list/t-crowdsourcing-issues.md
          - "topic-data": resources/ethics-reading-list/t-data.md
          - "topic-dual-use": resources/ethics-reading-list/t-dual-use.md
          - "topic-environmental-impact": resources/ethics-reading-list/t-environmental-impact.md
          - "topic-evaluation": resources/ethics-reading-list/t-evaluation.md
          - "topic-general-resources": resources/ethics-reading-list/t-general-resources.md
          - "topic-language-diversity": resources/ethics-reading-list/t-language-diversity.md
          - "topic-model-issues": resources/ethics-reading-list/t-model-issues.md
          - "topic-uncategorized": resources/ethics-reading-list/t-uncategorized.md
          - "type-post": resources/ethics-reading-list/type-post.md
          - "type-preprint": resources/ethics-reading-list/type-preprint.md
          - "type-published": resources/ethics-reading-list/type-published.md
          - "type-report": resources/ethics-reading-list/type-report.md
        - "Ethical Reviewing Recommendations":
          - resources/ethical-review-recommendations/index.md
        - "Ethics Committee Chairs Metadata at CL/NLP Conferences":
          - resources/chairs-metadata/index.md
  - Committee: committee.md
theme:
  name: material
  features:
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.indexes
    - navigation.top
    - navigation.prune
    # - navigation.sections
    # - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  icon:
    repo: fontawesome/brands/github
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.snippets
  - pymdownx.inlinehilite
  - pymdownx.critic
  - pymdownx.mark
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.details
  - pymdownx.smartsymbols
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.snippets
  - pymdownx.inlinehilite
  - pymdownx.critic
  - pymdownx.mark
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.details
  - pymdownx.smartsymbols
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

copyright: |
  &copy; 2025â€“2023 <a href="https://github.com/acl-org/ethics-website"  target="_blank" rel="noopener">ACL Ethics Committee</a>
  
# Additional configuration
extra:
 # status:
 #   new: Recently added
 #   deprecated: Deprecated
 # analytics:
 #   provider: google
 #   property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/acl-org/ethics-website
#    - icon: fontawesome/brands/docker
#      link: https://hub.docker.com/r/squidfunk/mkdocs-material/
#    - icon: fontawesome/brands/python
#      link: https://pypi.org/project/mkdocs-material/
#    - icon: fontawesome/brands/bluesky
#      link: https://bsky.app/profile/squidfunk.bsky.social
#    - icon: fontawesome/brands/mastodon
#      link: https://fosstodon.org/@squidfunk
#    - icon: fontawesome/brands/x-twitter
#      link: https://x.com/squidfunk
